### ISSUE TITLE
use FastP instead of FastQC and trim_galore

### ISSUE THREAD

**Issue by johnbradley** [bespin-workflows/exomeseq-gatk4#18]
User Request: 
> Removing FastQC and switching trim_galore to FastP will speed things up quite a bit and still generate the same information

FastP github repo: https://github.com/OpenGene/fastp

FastQC and trim_galore steps in the preprocessing sub-workflow:
https://github.com/bespin-workflows/exomeseq-gatk4/blob/f07a07037e7c162f117b3706614d885741a44518/subworkflows/exomeseq-gatk4-01-preprocessing.cwl#L112-L137

**Comment by dleehr** [comment]
Found a candidate docker image at https://hub.docker.com/r/nanozoo/fastp, but the underlying GitHub repo is gone, so I'm electing not to use this image

**Comment by dleehr** [comment]
https://hub.docker.com/r/zlskidmore/fastp/ looks 👍

**Comment by dleehr** [comment]
Actually I may go with biocontainers here: https://quay.io/repository/biocontainers/fastp

**Comment by johnbradley** [comment]
This has been resolved via PR #22
