### ISSUE TITLE
gatk4 exomseq error in joint-genotyping

### ISSUE THREAD

**Issue by johnbradley** [bespin-workflows/exomeseq-gatk4#6]
Had this error running the `exomeseq-gatk4.cwl` workflow: 
```
[joint-genotyping-pod-mwavwtip] ***********************************************************************
[joint-genotyping-pod-mwavwtip]
[joint-genotyping-pod-mwavwtip] A USER ERROR has occurred: only_output_calls_starting_in_intervals is not a recognized option
[joint-genotyping-pod-mwavwtip]
[joint-genotyping-pod-mwavwtip] ***********************************************************************
```

URL to the workflow ran: https://gist.githubusercontent.com/dleehr/7ff15cccb3276bbe58cc67ec200f2740/raw/258ec818d916936de5f8f162c7662929adb5d307/exomeseq-gatk4.cwl
This workflow was modified to increase memory in SortSam step to match GATK3 SortSam requirements.

Relavent code:
https://github.com/bespin-workflows/exomeseq-gatk4/blob/46b0ead5ff44fe87a2a3817c1d49a8c7e97ddc83/tools/GATK4/GATK4-GenotypeGVCFs.cwl#L48

GATK4 docs:
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.4.0/org_broadinstitute_hellbender_tools_walkers_GenotypeGVCFs.php#--only-output-calls-starting-in-intervals

Looks like this should be a simple change to `--only-output-calls-starting-in-intervals`.

Moved this issue from https://github.com/Duke-GCB/bespin-cwl/issues/78

**Comment by johnbradley** [comment]
Looks like there is another issue with this related to the `-V` argument.
In a test environment I fixed fixed the workflow to use the correct flag, but it failed with:
```
[joint-genotyping-pod-zevlqygz] ***********************************************************************
--
  | [joint-genotyping-pod-zevlqygz]
  | [joint-genotyping-pod-zevlqygz] A USER ERROR has occurred: Argument '[V, variant]' cannot be specified more than once.
  | [joint-genotyping-pod-zevlqygz]
  | [joint-genotyping-pod-zevlqygz] ***********************************************************************
```
We specified this as an array:
https://github.com/bespin-workflows/exomeseq-gatk4/blob/46b0ead5ff44fe87a2a3817c1d49a8c7e97ddc83/tools/GATK4/GATK4-GenotypeGVCFs.cwl#L55-L63

Perhaps we need to merge them into one file.
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.4.0/org_broadinstitute_hellbender_tools_walkers_GenotypeGVCFs.php#--variant

**Comment by johnbradley** [comment]
Question about passing multiple VCF files to GenotypeGVCF in GATK 4:
https://gatkforums.broadinstitute.org/gatk/discussion/comment/40228/#Comment_40228

>Run GenomicsDBImport to combine all GVCFs into a single VCF before running GenotypeGVCFs.

**Comment by dleehr** [comment]
Thanks for catching this. I didn't realize that GenotypeGVCF only takes one variant file now.

The relevant upstream WDL code is over here: https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/b6f86ebfeeb8990b2588b72f3ad869e93e218e5f/joint-discovery-gatk4-local.wdl#L383-L440, and it scatters across the array of intervals. I assumed the GenomicsDBImport step was an artifact of that, but we'll obviously need to add a step to merge variants before running GenotypeGVCFs.

**Comment by johnbradley** [comment]
I found a CWL workflow that does this transformation: https://github.com/wtsi-hgi/arvados-pipelines/blob/master/cwl/workflows/gatk-4.0.0.0-genomics-db-and-genotypegvcfs-per-interval.cwl#L29

**Comment by johnbradley** [comment]
Based on a suggestion from @dleehr I used CombineGVCFs instead of GenomicsDBImport. They perform the same operation and CombineGVCFs fits better with our overall workflow. Need to look at how this effected performance. CombineGVCFs docs: https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.4.0/org_broadinstitute_hellbender_tools_walkers_CombineGVCFs.php

**Comment by johnbradley** [comment]
Workflow finished joint-genotyping and hit another snag.
Error on `variant_recalibration_indels`step:
```
[step variant_recalibration_indels] Cannot make job: Invalid job input record:
--
  | the `resources` field is not valid because
  | ../bespin/job-data/workflow/exomeseq-gatk4.cwl:1526:33:   item is invalid because
  | ../bespin/job-data/workflow/exomeseq-gatk4.cwl:1532:37:     the `file` field is not valid because
  | ../bespin/job-data/workflow/exomeseq-gatk4.cwl:1532:37:       is not a dict
```

I think it's just needs a tweak the the defaults for resources:
https://github.com/bespin-workflows/exomeseq-gatk4/blob/46b0ead5ff44fe87a2a3817c1d49a8c7e97ddc83/subworkflows/exomeseq-gatk4-02-variantdiscovery.cwl#L137-L139

**Comment by dleehr** [comment]
> Error on `variant_recalibration_indels` step:

D'oh. I was hoping this wouldn't come back to bite me 😬. This Recordtype/dictionary was supposed to be an elegant way to bundle some fields with a File object and let CWL take care of the type checking. It took a lot of tweaking, but I'm pretty sure this worked at the time.

https://github.com/Duke-GCB/bespin-cwl/commits/master/tools/GATK4-VariantRecalibrator.cwl

That said, I don't think we can change the `File` type to a `string` type. Guess it depends on where the path gets resolved, but I'm inclined to take another pass at this.

**Comment by johnbradley** [comment]
I was able to switch the `File` to `string` and updated VariantRecalibrator in my PR:
https://github.com/bespin-workflows/exomeseq-gatk4/pull/8/files#diff-7c6b97cc33357c81b8855465d669af17 

Casting the `File` object to an appropriate `File` dict seems like it should be possible. I just haven't been able to find a way to do that in CWL.

**Comment by johnbradley** [comment]
I think it worked fine because the example passes the file in from the input job order:
https://github.com/bespin-workflows/exomeseq-gatk4/blob/44d83f93cd8fa7cfdcf2ddfa6435239a4eeb4c27/examples/tools/GATK4-VariantRecalibrator-INDELs.json#L25

**Comment by dleehr** [comment]
I think the problem we're going to hit is that a CWL CommandLineToolJob (and by extension, calrissian) will only see these `filepath` strings as strings. Instead, the WorkflowJob (e.g. cwltool process) will extract their path while parsing the workflow and pass the path along as a string to the CommandLineToolJob. But by that time, they're no longer `File`s for the tool, so it won't know they need to be mounted into the container.

**Comment by johnbradley** [comment]
I tried to fix this issue by passing the records as job order inputs to the workflow.
Unfortunately the input files require the `.idx` secondary files.
[CommandInputParameter](https://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter) has `type` and `secondaryFile` properties.

But since we are passing an array of [InputRecordField](https://www.commonwl.org/v1.0/CommandLineTool.html#InputRecordField) we only have a `type` property.

**Comment by johnbradley** [comment]
Looks like CWL 1.1 will allow using secondaryFile with records: https://github.com/common-workflow-language/cwltool/pull/481

**Comment by johnbradley** [comment]
I found a CWL VariantRecalibrator CommandLineTool where the per file settings were hard coded:
https://github.com/h3abionet/h3agatk/blob/6dcce32780f7a31ef860884635ac85557c4c5453/tools/GATK-VariantRecalibrator-Indels.cwl#L59-L66

I don't like how this embeds the configuration for the files in the lowest level CommandLineTool.

**Comment by dleehr** [comment]
See also https://github.com/bespin-workflows/exomeseq-gatk3/blob/f3639c7024b2ddaf64389428dd552b3426468a13/tools/GATK-VariantRecalibrator-Indels.cwl#L74-L81 😄
